import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./index.css";
import Navbar from "src/components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Next JS | Appwrite",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className='px-2'>
				<div>
					<Toaster
						position='top-center'
						reverseOrder={false}
					/>
				</div>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
